# kubectl create -f k8-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple -calculator -deployment
  namespace: default
  labels:
    app: simple -calculator -deployment
spec:
  selector:
    matchLabels:
      app: simple -calculator -deployment
    replicas: 3
    template:
      metadata:
        labels:
          app: simple -calculator -deployment
      spec:
        containers:
          - name: simple -calculator -deployment
            image: simple -calculator -image:v2
            imagePullPolicy: Never
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                cpu: 100m
                memory: 100Mi
              ports:
                - name: nodejs -port
                  containerPort: 3000
                  protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: simple -calculator -service -4
  namespace: default
spec:
  selector:
    app: simple -calculator -deployment
  type: NodePort
  ports:
    - targetPort: nodejs -port
      protocol: TCP
      port: 3000
