# kubectl create -f k8-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: simple -calculator -service -3
  namespace: default
spec:
  selector:
    app: simple -calculator -pod -3
    type: NodePort
    ports:
      - targetPort: nodejs -port
        protocol: TCP
        port: 3000
